services:
  # Run with: docker compose run --rm metasploit
  metasploit:
    image: "docker.io/heywoodlh/metasploit:latest"
    command: "msfconsole --quiet --execute-command 'db_connect postgres:msf@db:5432/msf'"
    tty: true
    stdin_open: true
    volumes:
      - msf_data:/root/.msf4
    links:
      - db
  db:
    image: "docker.io/postgres:14"
    volumes:
      - msf_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: msf
      POSTGRES_PASSWORD: msf

volumes:
  msf_database:
  msf_data:
