services:
  # Run with: docker compose run --rm metasploit
  metasploit:
    build: .
    command: "msfconsole --quiet --execute-command 'db_connect postgres:msf@db:5432/msf'"
    tty: true
    stdin_open: true
    volumes:
      - msf_data:/home/msf/.msf4
      - msf_nix:/nix
    ports:
      - 1337:1337 # C&C port
    environment:
      SUDO: "false"
    links:
      - db
  db:
    image: "docker.io/postgres:14"
    volumes:
      - msf_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: msf
      POSTGRES_PASSWORD: msf

volumes:
  msf_database:
  msf_data:
  msf_nix:
