FROM debian:latest
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  systemd systemd-sysv dbus dbus-user-session \
  && rm -rf /var/lib/apt/lists/*
COPY systemd.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
