[supervisord]
nodaemon=true
loglevel=info
logfile=/etc/supervisor/supervisord.log

[program:dockerd]
command=/dockerd.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:spindle]
command=/spindle.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
