name: buildx

on:
  schedule:
    - cron: "0 0 * * Sun"
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current month
        id: date
        run: echo "::set-output name=date::$(date +%Y_%m_snapshot)"
      -
        name: Build and push bitlbee-libpurple
        uses: docker/build-push-action@v2
        with:
          context: bitlbee-libpurple
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/bitlbee-libpurple:latest,heywoodlh/bitlbee-libpurple:${{ steps.date.outputs.date }}
      -
        name: Build and push port-crawler
        uses: docker/build-push-action@v2
        with:
          context: port-crawler
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/port-crawler:latest,heywoodlh/port-crawler:${{ steps.date.outputs.date }}
      -
        name: Build and push aerc
        uses: docker/build-push-action@v2
        with:
          context: aerc
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/aerc:latest,heywoodlh/aerc:${{ steps.date.outputs.date }}
      -
        name: Build and push hydroxide
        uses: docker/build-push-action@v2
        with:
          context: hydroxide
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/hydroxide:latest,heywoodlh/hydroxide:${{ steps.date.outputs.date }}
      -
        name: Build and push metasploit
        uses: docker/build-push-action@v2
        with:
          context: metasploit
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/metasploit:latest,heywoodlh/metasploit:${{ steps.date.outputs.date }}
      -
        name: Build and push tomnomnom-tools
        uses: docker/build-push-action@v2
        with:
          context: tomnomnom-tools
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/tomnomnom-tools:latest,heywoodlh/tomnomnom-tools:${{ steps.date.outputs.date }}
      -
        name: Build and push links
        uses: docker/build-push-action@v2
        with:
          context: links
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/links:latest,heywoodlh/links:${{ steps.date.outputs.date }}
      -
        name: Build and push openssh
        uses: docker/build-push-action@v2
        with:
          context: openssh
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/openssh:latest,heywoodlh/openssh:${{ steps.date.outputs.date }}
      -
        name: Build and push evilginx2
        uses: docker/build-push-action@v2
        with:
          context: evilginx2
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/evilginx2:latest,heywoodlh/evilginx2:${{ steps.date.outputs.date }}
      -
        name: Build and push second
        uses: docker/build-push-action@v2
        with:
          context: second
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/second:latest,heywoodlh/second:${{ steps.date.outputs.date }}
      -
        name: Build and push cloudtube
        uses: docker/build-push-action@v2
        with:
          context: cloudtube
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/cloudtube:latest,heywoodlh/cloudtube:${{ steps.date.outputs.date }}
      -
        name: Build and push red
        uses: docker/build-push-action@v2
        with:
          context: red
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/red:latest,heywoodlh/red:${{ steps.date.outputs.date }}
      -
        name: Build and push flan-scan
        uses: docker/build-push-action@v2
        with:
          context: flan-scan
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: heywoodlh/flan-scan:latest,heywoodlh/flan-scan:${{ steps.date.outputs.date }}
