name: dev-buildx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/dockerfiles
        uses: actions/checkout@master
        with:
          name: heywoodlh/dockerfiles
          repository: heywoodlh/dockerfiles
          path: ./dockerfiles

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Setup nix magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      -
        name: Update flake
        run: |
          cd dockerfiles/dev
          nix flake update
          git add flake.lock

      -
        name: Get current month
        run: echo date=$(date +%Y_%m) >> $GITHUB_ENV

      -
        name: Build and push heywoodlh/dev
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/dev:latest,heywoodlh/dev:${{ env.date }}
